Выполнил задание Lesson10
Safer68/javaCore pull request #12
Opened 2021-12-08 20:34 UTC by Safer68

2021-12-08 20:35 UTC, Safer68 commented
![](https://github.trello.services/images/mini-trello-icon.png) [10 Практическая часть 07.12.2021](https://trello.com/c/DNz1Xcla/345-10-%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F-%D1%87%D0%B0%D1%81%D1%82%D1%8C-07122021)

2021-12-12 17:53 UTC, Vlasik-Henadzi requested changes

2021-12-12 17:53 UTC, Vlasik-Henadzi commented on src/Lesson10/Task26.java
> +    String string;
модификатор доступа поставить

2021-12-12 17:53 UTC, Vlasik-Henadzi commented on src/Lesson10/Seasons.java
> +    Springt("Весна", 92), Summer("Лето", 92),
SPRING, SUMMER...

2021-12-12 17:53 UTC, Vlasik-Henadzi commented on src/Lesson10/Task28.java
> +    String string;
модификатор доступа

2021-12-12 17:53 UTC, Vlasik-Henadzi commented on src/Lesson10/Task28.java
> +        n.append(string.charAt(string.length() - 1));
а если последний символ будет пробел?

2021-12-12 17:53 UTC, Vlasik-Henadzi commented on src/Lesson10/Task28.java
> +                n.append(string.charAt(i - 1));
а если будут два пробела подряд идти?

2021-12-12 17:53 UTC, Vlasik-Henadzi commented on src/Lesson10/Task29.java
> +        Pattern pattern = Pattern.compile("0x.+?\\b");
0X2323... - это тоже 16 ричное число

2021-12-14 15:55 UTC, merged