Задание Lesson4 выполнено
Safer68/javaCore pull request #4
Opened 2021-11-17 19:23 UTC by Safer68

2021-11-17 19:26 UTC, Safer68 commented
![](https://github.trello.services/images/mini-trello-icon.png) [4 Практическая часть 16.11.2021](https://trello.com/c/EZDifvAA/140-4-%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F-%D1%87%D0%B0%D1%81%D1%82%D1%8C-16112021)

2021-11-18 06:30 UTC, Vlasik-Henadzi requested changes

2021-11-18 06:30 UTC, Vlasik-Henadzi commented on src/Lesson4/LegalEntity.java
> +        double profit = proceeds - ((double)proceeds / 100) * taxPercentage;
можно в одну строку написать
return proceeds - ((double)proceeds / 100) * taxPercentage;

2021-11-18 06:30 UTC, Vlasik-Henadzi commented on src/Lesson4/Bookkeeping.java
> +        System.out.println(legalEntity.getProceeds());
если метод не используешь, то удаляй его

2021-11-18 06:30 UTC, Vlasik-Henadzi commented on src/Lesson4/Bookkeeping.java
> +//        bookkeeping.balanceCompany(ojsc);
не нужный код удаляй

2021-11-21 17:08 UTC, merged